version: "{build}"
clone_folder: c:\gopath\src\github.com\mackerelio\mkr
environment:
  VERSION: go1.14.2
  GOPATH: c:\gopath
  GOROOT: c:\tools\go
  GO111MODULE: on
build: off
install:
  - appveyor DownloadFile https://dl.google.com/go/%VERSION%.windows-amd64.zip
  - 7z x %VERSION%.windows-amd64.zip -oC:\tools\
  - set PATH=%GOROOT%\bin;%GOPATH%\bin;C:\msys64\mingw64\bin;%PATH%
test_script:
  - go test -v ./...
