name: Build

on:
  push:
    branches:
    - master
    tags:
    - v*
  pull_request:
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: golangci/golangci-lint-action@v2
      with:
        version: v1.35
  test:
    strategy:
      matrix:
        os: ['ubuntu-18.04', 'macOS-10.15', 'windows-2019']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - run: |
        go test -race -covermode atomic -coverprofile=profile.cov ./...
      shell: bash
    - uses: shogo82148/actions-goveralls@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-profile: profile.cov
        parallel: true
        job-number: ${{ strategy.job-index }}
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: shogo82148/actions-goveralls@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
    steps:
    - run: |
        sudo apt-get update
        sudo apt-get install -y \
          rpm devscripts debhelper fakeroot \
          crossbuild-essential-arm64 crossbuild-essential-armhf
        mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - uses: actions/checkout@v2
    - run: make all
    - uses: actions/upload-artifact@v2
      with:
        name: linux-build-artifacts
        path: |
          ~/rpmbuild/RPMS/*/*.rpm
          packaging/*.deb
          snapshot/*.zip
          snapshot/*.tar.gz
          build/*.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: linux-build-artifacts
        path: artifacts/

    - uses: mackerelio/staging-release-update-action@main
      if: github.ref == 'refs/heads/master'
      with:
        directory: artifacts/
        github-token: ${{ secrets.GITHUB_TOKEN }}
        tag: staging

    - uses: mackerelio/create-release-action@main
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        directory: artifacts/
        github-token: ${{ secrets.GITHUB_TOKEN }}
        tag-prefix: 'refs/tags/v'
        bump-up-branch-prefix: 'bump-version-'

    - name: update homebrew-mackerel-agent
      if: startsWith(github.ref, 'refs/tags/v')
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.MACKERELBOT_GITHUB_TOKEN }}
        event-type: release
        client-payload: '{"product": "mkr"}'

    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,action,eventName,ref,workflow,job,took
        username: mkr-release
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.MACKEREL_SLACK_WEBHOOK_URL }}
